<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="6" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="446" started-at="2018-06-27T12:19:39Z" finished-at="2018-06-27T12:19:40Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="446" started-at="2018-06-27T12:19:39Z" finished-at="2018-06-27T12:19:40Z">
      <class name="com.qainfotech.tap.training.snl.api.SnlTest">
        <test-method status="PASS" signature="beforeStart()[pri:0, instance:com.qainfotech.tap.training.snl.api.SnlTest@15d3402]" name="beforeStart" is-config="true" duration-ms="263" started-at="2018-06-27T12:19:39Z" finished-at="2018-06-27T12:19:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeStart -->
        <test-method status="PASS" signature="boardRegister()[pri:0, instance:com.qainfotech.tap.training.snl.api.SnlTest@15d3402]" name="boardRegister" duration-ms="21" started-at="2018-06-27T12:19:40Z" finished-at="2018-06-27T12:19:40Z">
          <exception class="com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption">
            <message>
              <![CDATA[The board already has maximum allowed Player: 4]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption: The board already has maximum allowed Player: 4
at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:66)
at com.qainfotech.tap.training.snl.api.SnlTest.boardRegister(SnlTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- boardRegister -->
        <test-method status="FAIL" signature="checkCrossTurnInMatch()[pri:0, instance:com.qainfotech.tap.training.snl.api.SnlTest@15d3402]" name="checkCrossTurnInMatch" duration-ms="29" started-at="2018-06-27T12:19:40Z" finished-at="2018-06-27T12:19:40Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Expected exception of type class com.qainfotech.tap.training.snl.api.InvalidTurnException but got org.json.JSONException: JSONObject["data"] not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Expected exception of type class com.qainfotech.tap.training.snl.api.InvalidTurnException but got org.json.JSONException: JSONObject["data"] not found.
at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1129)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:612)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.json.JSONException: JSONObject["data"] not found.
at org.json.JSONObject.get(JSONObject.java:471)
at org.json.JSONObject.getJSONObject(JSONObject.java:636)
at com.qainfotech.tap.training.snl.api.SnlTest.checkCrossTurnInMatch(SnlTest.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
... 19 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkCrossTurnInMatch -->
        <test-method status="PASS" signature="checkExistingPlayer()[pri:0, instance:com.qainfotech.tap.training.snl.api.SnlTest@15d3402]" name="checkExistingPlayer" duration-ms="8" started-at="2018-06-27T12:19:40Z" finished-at="2018-06-27T12:19:40Z">
          <exception class="com.qainfotech.tap.training.snl.api.PlayerExistsException">
            <message>
              <![CDATA[Player 'ac' already exists on board]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.PlayerExistsException: Player 'ac' already exists on board
at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:71)
at com.qainfotech.tap.training.snl.api.SnlTest.checkExistingPlayer(SnlTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.PlayerExistsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkExistingPlayer -->
        <test-method status="PASS" signature="checkInProgress()[pri:0, instance:com.qainfotech.tap.training.snl.api.SnlTest@15d3402]" name="checkInProgress" duration-ms="9" started-at="2018-06-27T12:19:40Z" finished-at="2018-06-27T12:19:40Z">
          <exception class="com.qainfotech.tap.training.snl.api.GameInProgressException">
            <message>
              <![CDATA[New player cannot join since the game has started]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.GameInProgressException: New player cannot join since the game has started
at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:74)
at com.qainfotech.tap.training.snl.api.SnlTest.checkInProgress(SnlTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.GameInProgressException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkInProgress -->
        <test-method status="PASS" signature="registerPlayertest()[pri:0, instance:com.qainfotech.tap.training.snl.api.SnlTest@15d3402]" name="registerPlayertest" duration-ms="8" started-at="2018-06-27T12:19:40Z" finished-at="2018-06-27T12:19:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerPlayertest -->
        <test-method status="PASS" signature="validRolltest()[pri:0, instance:com.qainfotech.tap.training.snl.api.SnlTest@15d3402]" name="validRolltest" duration-ms="36" started-at="2018-06-27T12:19:40Z" finished-at="2018-06-27T12:19:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validRolltest -->
      </class> <!-- com.qainfotech.tap.training.snl.api.SnlTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
